feat: support additional management policy combination
crossplane/crossplane-runtime pull request #788
Opened 2024-11-10 08:38 UTC by man-ish-k

### Description of your changes
Add two new management policy combinations to support safer resource importing and external lifecycle management scenarios:

1. **Import Mode**: A new policy combination that allows safe importing of existing resources by only permitting observation and late initialization, without making any changes to the external resource.
   - Actions: `[Observe, LateInitialize]`
   - Use case: Safely discover and import existing cloud resources into Crossplane without risk of modifying them

2. **External Lifecycle Management**: A policy combination for resources whose lifecycle (creation/deletion) is managed outside of Crossplane, but allows Crossplane to make updates and track state.
   - Actions: `[Observe, Update, LateInitialize]`
   - Use case: Integration with external provisioning systems while maintaining Crossplane's ability to manage resource configuration

Fixes #681, 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `earthly +reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] Linked a PR or a [docs tracking issue] to [document this change].
- [ ] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/main/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/main/contributing#checklist-cheat-sheet

2025-01-27 15:30 UTC, jake-ciolek commented
Hi @jbw976 and @negz . Could you please have a look at this one? It's been open for a while. Thanks!

2025-02-12 09:16 UTC, lsviben requested changes
Firstly, sorry for waiting that long for a review, this slipped my mind and I got reminded just recently 🙏 .

The policies added make sense to me. 

We need to add the unit tests in the right place to check the reconciler flow with the new policies.

2025-02-12 09:16 UTC, lsviben commented on pkg/reconciler/managed/policies_test.go
> +func TestManagementPoliciesResolver_Validate(t *testing.T) {
All these tests below exist in [reconciler_test.go](https://github.com/crossplane/crossplane-runtime/blob/main/pkg/reconciler/managed/reconciler_test.go). I agree that as at one point the policy resolver moved to `policies.go` that its tests should reside in `policies_test.go`. But we shouldnt duplicate and that can be done as a separate change. 

The unit tests that actually need to be added is testing the new combinations in [reconciler_test.go](https://github.com/crossplane/crossplane-runtime/blob/main/pkg/reconciler/managed/reconciler_test.go) `TestReconcile`.

2025-02-12 16:36 UTC, man-ish-k commented on pkg/reconciler/managed/policies_test.go
> +func TestManagementPoliciesResolver_Validate(t *testing.T) {
Thanks @lsviben I have made the requested changes.

2025-02-25 08:30 UTC, lsviben approved these changes
Looks good! Thanks @man-ish-k ! 🎉

2025-02-25 08:41 UTC, turkenh approved these changes

2025-02-25 08:41 UTC, merged